package com.galleryorganizer.data.db

import org.json.JSONObject

/**
 * Builds an *old* version of the schema from the JSON Room exported at the time, so
 * migration tests never drift from what actually shipped.
 *
 * This deliberately does not use `MigrationTestHelper`: that class wants an
 * `Instrumentation` and reads the schema from the test APK's assets, which is awkward to
 * arrange for JVM-only tests. Reading the same exported JSON directly gives the identical
 * guarantee with no device dependency. `app/schemas` is on the unit-test resource path —
 * see `app/build.gradle.kts`.
 */
object SchemaBundle {

    private const val SCHEMA_DIR = "com.galleryorganizer.data.db.AppDatabase"

    /** Creates every table, index and view of schema [version] via [execSQL]. */
    fun create(version: Int, execSQL: (String) -> Unit): String {
        val database = JSONObject(read(version)).getJSONObject("database")

        val entities = database.getJSONArray("entities")
        for (i in 0 until entities.length()) {
            val entity = entities.getJSONObject(i)
            val table = entity.getString("tableName")
            execSQL(entity.getString("createSql").replace(TABLE_NAME_PLACEHOLDER, table))

            val indices = entity.optJSONArray("indices") ?: continue
            for (j in 0 until indices.length()) {
                execSQL(
                    indices.getJSONObject(j).getString("createSql")
                        .replace(TABLE_NAME_PLACEHOLDER, table),
                )
            }
        }

        val views = database.optJSONArray("views")
        if (views != null) {
            for (i in 0 until views.length()) {
                val view = views.getJSONObject(i)
                execSQL(
                    view.getString("createSql")
                        .replace("\${VIEW_NAME}", view.getString("viewName")),
                )
            }
        }

        // Room refuses to open a database whose identity it cannot confirm, so the
        // bookkeeping table has to be written exactly as Room would have written it.
        val identityHash = database.getString("identityHash")
        execSQL(
            "CREATE TABLE IF NOT EXISTS room_master_table " +
                "(id INTEGER PRIMARY KEY, identity_hash TEXT)",
        )
        execSQL(
            "INSERT OR REPLACE INTO room_master_table (id, identity_hash) " +
                "VALUES(42, '$identityHash')",
        )
        return identityHash
    }

    private fun read(version: Int): String {
        val path = "$SCHEMA_DIR/$version.json"
        val stream = checkNotNull(javaClass.classLoader?.getResourceAsStream(path)) {
            "Exported Room schema $path is missing. It is generated by KSP into " +
                "app/schemas and must be committed — migration tests are worthless " +
                "without the schema that actually shipped."
        }
        return stream.bufferedReader().use { it.readText() }
    }

    private const val TABLE_NAME_PLACEHOLDER = "\${TABLE_NAME}"
}
